### PR TITLE
feat: Better embeddings with FastEmbed-rs

### PR DESCRIPTION
**Pull request by Anush008**
## Description

This PR intends to improve the embedding generation of the project using https://github.com/Anush008/fastembed-rs. A library that downloads optimized embedding models and provides an interface for generating sentence embeddings. The model used will be https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2.

**Changes:**
* The local model and tokenizer files have been deleted, as the library downloads models optimised by Qdrant. `ort`, `ndarray` dependencies have been removed. `fastembed` uses them under the hood. 7c3db85855b391e4111f65d3e4e266b9e7241c7d
* The embedding generation logic using `ort` has been replaced with `fastembed`. 28f499a8c913d7d22d9257fb8d34228a7beab2af
* README.md has been updated to reflect the changes. 03e580e7c8beeabd646d83b91a7f9fb1bbb9822e

**Benefits**
* More accurate semantic code retrieval as the embedding quality improves. 
* Results in much better answers to user queries. 176463d532dcde1ec8ca9b276c39d15c044a4440.

**Cons**
* The model is larger. Approximately 70MB. The current one is 18MB due to rigorous quantization.
* This will result in longer embedding generation times.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
N/A

## Mobile & Desktop Screenshots/Recordings
N/A

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
We need to update the rust toolchain used for the docker image as well.

Looks like this is using some newer features in Rust: I got some errors that bubbled up from `ort` related to using unstable features when building locally:

```
use of unstable library feature 'cstr_is_empty' 
```

on `rustc 1.70.0 (90c541806 2023-05-31)`. But once I updated my rustc version to 1.73, it compiled.

This error seems to persist when building the image with `make local-image`

**Comment by Anush008** [comment]
@jpmcb, I've bumped the version. The build failed for me too when using Rust 1.70.
1.71 worked fine. I've bumped it to the latest stable release, that is 1.73.

**Review by jpmcb — APPROVED** [review]
Yeah, the latest stable should be good 👍🏼 this looks good! Great work!!

**Review by brandonroberts — APPROVED** [review]
🤖

**Pull request merged**
